### ISSUE TITLE
Snapshot restore: The current error message is not very helpful

### ISSUE THREAD

**Issue by rck** [LINBIT/linstor-proxmox#10]
`DRBD snapshot rollback is not implemented, please use 'linstor' to recover your data, use 'qm unlock' to unlock your VM at /usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm line 441`

If it can't be done automatically, could it perhaps include some hints on how to do the rollback manually?

_Originally posted by @elonen in https://github.com/LINBIT/linstor-proxmox/issues/5#issuecomment-427669809_

**Comment by elonen** [comment]
Any further pointers (beyond `qm unlock`) as to how it's supposed to be done would be nice.

I read the documentation and understood that the (only?) way to restore a snapshot with LINSTOR is to create a new resource, but it didn't seem very useful as I couldn't figure out how to attach restored copy (or any arbitrary resources) back into a VM (Proxmox tends to say "unable to parse lvm volume name"). Guess it would need to be renamed as "vm-NNN-disk-N", but there doesn't seem to be commands to rename resources in LINSTOR. I ended up `dd`ing contents back and forth, and recreating the whole virtual HDD volume. LINSTOR docs are indeed extensive, but Proxmox specific parts don't seem to cover this.

**Comment by rck** [comment]
Currently the only way is to restore such a snapshot to a new DRBD resource. I'm sure I explained that in the release mail on our ML back then when it was still drbdmanage and not LINSTOR: This is whole thing is meant to be used in a total "last resort" scenario. When you are happy to get to the data somehow, to then copy it to an image or whatever. It is, as of now, **not** meant to be used regularly as part of normal operation.

This will change at some point when LINSTOR supports in place snapshot rollback. Then it will be possible to do proper Proxmox integration. Till then, basically don't even use it (except for such "last resort" scenarios). And that is also why I'm reluctant to document something that is essentially not ready to be used by the broader community. It is a) you know exactly what is (and what not), and you are able to use it, because you know Proxmox and LINSTOR well enough. Then you don't need additional help. b) You don't know that, then you should not use it.

As I hope this is now sufficiently explained, and we already have a "in place snapshots" tracking ticket, I close this one.
