### ISSUE TITLE
Wishlist: DRBD quorum options

### ISSUE THREAD

**Issue by elonen** [LINBIT/linstor-proxmox#12]
With DRBD 9's nice quorum features, it would be great if linstor-proxmox provided a UI for them. Specifically, IO errors or freeze on quorum loss, or perhaps even automatic log + `qm stop` / `kill -KILL` on the attached VM if the plugin can perform them.

**Comment by rck** [comment]
There is no interface in the GUI we could attach to, so the GUI is out. For the rest, one can define "quorum handlers" on the CLI.
