### ISSUE TITLE
No content shown in proxmox GUI

### ISSUE THREAD

**Issue by scambra** [LINBIT/linstor-proxmox#20]
Content for DRBD storage is empty. Same for pvesm list drbdpool command, only warning is displayed.

```
$ sudo pvesm list drbdpool
Plugin "PVE::Storage::Custom::LINSTORPlugin" is implementing an older storage API, an upgrade is recommended
```

I think it was working before, I don't remember when it stopped working, when I upgrade proxmox and got this warning about old API, when I upgraded to linstor 0.9, or sometime else.

![image](https://user-images.githubusercontent.com/20515/60574399-dca64a80-9d79-11e9-8d93-44bef0f31fea.png)

Package versions:
```
ii  linstor-client     0.9.8-1      all          Linstor client command line tool
ii  linstor-common     0.9.12-1     all          DRBD distributed resource management utility
ii  linstor-proxmox    3.0.3-1      all          DRBD distributed resource management utility
ii  linstor-satellite  0.9.12-1     all          DRBD distributed resource management utility
ii  python-linstor     0.9.8-1      all          Linstor python api library
```

**Comment by rck** [comment]
Does LINSTOR itself work? Try to create a 10MB resource deployed on all nodes on the drbdpool via the linstor commandline client.

Quite frankly I don't know if the GUI ever showed something there. As these versions have not been releases yesterday, and because nobody of our users shouted at us on the mailing list, I don't think it is a regression. Hm.

**Comment by scambra** [comment]
Yes linstor works, I can create new resources

**Comment by zsmaczko** [comment]
Hi, the same here without the warning message:
root@pve1:~# pvesm status
Name             Type     Status           Total            Used       Available        %
drbdpool         drbd     active     11676942336       674441996     11002500340    5.78%
local             dir     active      5655662720       147766528      5507896192    2.61%
local-zfs     zfspool     active      5508241628          345384      5507896244    0.01%
root@pve1:~# pvesm list drbdpool 
root@pve1:~# 
It WAS content here and in the GUI before I run apt-get upgrade.

**Comment by zsmaczko** [comment]
Package versions are the same.

**Comment by netdox** [comment]
Hi, I've the same issue on my first setup for testing with 3 nodes 

> $ pvesm status
>Plugin "PVE::Storage::Custom::LINSTORPlugin" is implementing an older storage API, an upgrade is recommended
>Name            Type     Status           Total            Used       Available        %
>ISO              dir     active        20010832         8939608        10031660   44.67%
>drbdpool        drbd     active       224395264         4106434       220288830    1.83%
>local            dir     active        20010832         8939608        10031660   44.67%

Package version same like @scambra

Hopefully @rck can fix it
Thanks & best regards
Sebastian

**Comment by rck** [comment]
Thanks for the reports. Finally time to switch to the LINSTOR REST-API and the "new" Proxmox API. This might take a bit, but I'm currently looking at it.

**Comment by rck** [comment]
Could somebody try this branch/PR? This would be a quick fix before actually switching to the REST API (which will take several days I guess). It fixes the issue for me:
https://github.com/LINBIT/linstor-proxmox/tree/rdvdfix

- just overwrite `/usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm` with the one from the branch.
- `systemctl restart pvedaemon`

**Comment by zsmaczko** [comment]
I've tried it just like you wrote (.pm file overwritten, pvedaemon restarted). The warning message came back and no other change happened.
```
root@pve1:~# pvesm status
Plugin "PVE::Storage::Custom::LINSTORPlugin" is implementing an older storage API, an upgrade is recommended
Name             Type     Status           Total            Used       Available        %
drbdpool         drbd     active     11676942336       674441948     11002500388    5.78%
local             dir     active      5656007936       147764736      5508243200    2.61%
local-zfs     zfspool     active      5508243296              96      5508243200    0.00%
nfs1              nfs     active      5654514688      3285325824      2369188864   58.10%
root@pve1:~# pvesm list drbdpool 
Plugin "PVE::Storage::Custom::LINSTORPlugin" is implementing an older storage API, an upgrade is recommended
root@ov0pve1:~# 

```

**Comment by netdox** [comment]
> Could somebody try this branch/PR? This would be a quick fix before actually switching to the REST API (which will take several days I guess). It fixes the issue for me:
> https://github.com/LINBIT/linstor-proxmox/tree/rdvdfix
> 
> * just overwrite `/usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm` with the one from the branch.
> * `systemctl restart pvedaemon`

Hi guys,

I get the same error like before on the shell after exchange the .pm, but now the vmdisk it's shown:

> $ pvesm list drbdpool
>Plugin "PVE::Storage::Custom::LINSTORPlugin" is implementing an older storage API, an upgrade is recommended
>drbdpool:vm-100-disk-2   raw 4294967296 100


I can also see the vmdisk in the Storage Content of Proxmox Gui in the drbdpool.
![proxmox-stroage](https://user-images.githubusercontent.com/52862324/61210374-95ff0b80-a6fc-11e9-8d65-86763a03e768.png)

Thanks for the fast fixing @rck 

best regards
Sebastian

**Comment by rck** [comment]
@zsmaczko It is expected that it does not fix the warning. That is something completely different. I had to "click around" and "refresh" before it was visible in the GUI.

@netdox Thanks for testing, I will merge it and release that one.

**Comment by zsmaczko** [comment]
The last fix works as expected:
`root@pve1:~# pvesm status
Plugin "PVE::Storage::Custom::LINSTORPlugin" is implementing an older storage API, an upgrade is recommended
Name             Type     Status           Total            Used       Available        %
drbdpool         drbd     active     11676942336       674441948     11002500388    5.78%
local             dir     active      5656007936       147764992      5508242944    2.61%
local-zfs     zfspool     active      5508243112              96      5508243016    0.00%
nfs1              nfs     active      5654521600      3285326208      2369195392   58.10%
root@pve1:~# pvesm list drbdpool 
Plugin "PVE::Storage::Custom::LINSTORPlugin" is implementing an older storage API, an upgrade is recommended
drbdpool:vm-100-disk-0        raw 4294967296 100
drbdpool:vm-16000006-disk-1   raw 85899345920 16000006
drbdpool:vm-16000172-disk-1   raw 32212254720 16000172
drbdpool:vm-16000177-disk-1   raw 107374182400 16000177
drbdpool:vm-16000179-disk-1   raw 33285996544 16000179
drbdpool:vm-16003010-disk-1   raw 42949672960 16003010
`
