### ISSUE TITLE
LINSTORPlugin still get old plugin from repo

### ISSUE THREAD

**Issue by frenzymind** [LINBIT/linstor-proxmox#22]
Hi!
I follow theres instruction: https://docs.linbit.com/docs/users-guide-9.0/#s-proxmox-ls-install
I install like this:
`wget -O- https://packages.linbit.com/package-signing-pubkey.asc | apt-key add -`
`PVERS=5 && echo "deb http://packages.linbit.com/proxmox/ proxmox-$PVERS drbd-9.0" > \
	/etc/apt/sources.list.d/linbit.list`
`apt update && apt install linstor-proxmox`

And I have `linstor-proxmox/unknown,now 3.0.4-1 all [installed]` at the end. but somehow I dont get last update from here with APIVER 2 fix.
What I do wrong? Change file manually is not good idea (I do this and problem disappear), but again, why repo has old version ?

**Comment by rck** [comment]
That is easy, I simply did not officially release the version that is on master (which provides APIVER2 compatibility). I wanted to have some "works for me"s first. Anyways, it basically just removes the warning, you don't get any other benefits. And as I'm in the middle of rewriting the whole thing to use LINSTOR's REST API, the APIVER2 thing most likely will not get a release on its own.

**Comment by frenzymind** [comment]
Thanks for reply. 
But for me it is also fix visual issue with question mark in the storage icon and status "unknown" on hover it.
