### ISSUE TITLE
Clone operation does not cleanup resource if stopped/interrupted

### ISSUE THREAD

**Issue by acidrop** [LINBIT/linstor-proxmox#23]
ii  linstor-proxmox                      4.0.0~rc1-1 

Cloning a qemu-kvm vm or a lxc container works as expected. However, if cloning operation is cancelled or interrupted for whatever reason, linstor-proxmox plugin does not cleanup the resource. This used to work with the previous plugin version.

Steps to reproduce:
===============
- Create a VM or CT (or use an existing one)
- Clone it
- Once cloning operation starts, cancel it by pressing stop button

Manual cleanup steps:
=================
- Issue qm or pct unlock <vmid>
- Remove the stale VM or CT via GUI or CLI
- Issue linstor rd d res_name
- Verify that drbd res_name was deleted via drbdtop

Logs:
====
```
create full clone of drive scsi0 (drbdstorage:vm-101-disk-1)
transferred: 0 bytes remaining: 10737418240 bytes total: 10737418240 bytes progression: 0.00 %
transferred: 109521666 bytes remaining: 10627896574 bytes total: 10737418240 bytes progression: 1.02 %
transferred: 217969590 bytes remaining: 10519448650 bytes total: 10737418240 bytes progression: 2.03 %
transferred: 327491256 bytes remaining: 10409926984 bytes total: 10737418240 bytes progression: 3.05 %
transferred: 435939180 bytes remaining: 10301479060 bytes total: 10737418240 bytes progression: 4.06 %
transferred: 545460846 bytes remaining: 10191957394 bytes total: 10737418240 bytes progression: 5.08 %
transferred: 653908770 bytes remaining: 10083509470 bytes total: 10737418240 bytes progression: 6.09 %
transferred: 763430436 bytes remaining: 9973987804 bytes total: 10737418240 bytes progression: 7.11 %
transferred: 871878361 bytes remaining: 9865539879 bytes total: 10737418240 bytes progression: 8.12 %
transferred: 981400027 bytes remaining: 9756018213 bytes total: 10737418240 bytes progression: 9.14 %
transferred: 1090921693 bytes remaining: 9646496547 bytes total: 10737418240 bytes progression: 10.16 %
transferred: 1199369617 bytes remaining: 9538048623 bytes total: 10737418240 bytes progression: 11.17 %
transferred: 1308891283 bytes remaining: 9428526957 bytes total: 10737418240 bytes progression: 12.19 %
transferred: 1417339207 bytes remaining: 9320079033 bytes total: 10737418240 bytes progression: 13.20 %
transferred: 1526860873 bytes remaining: 9210557367 bytes total: 10737418240 bytes progression: 14.22 %
transferred: 1635308797 bytes remaining: 9102109443 bytes total: 10737418240 bytes progression: 15.23 %
transferred: 1744830464 bytes remaining: 8992587776 bytes total: 10737418240 bytes progression: 16.25 %
error with cfs lock 'storage-drbdstorage': Could not delete resource vm-106-disk-1, because:
[{"ret_code":-4611686018373385243,"message":"Resource 'vm-106-disk-1' on node 'pve3' is still in use.","cause":"Resource is mounted/in use.","correction":"Un-mount resource 'vm-106-disk-1' on the node 'pve3'.","details":"Resource definition: vm-106-disk-1","error_report_ids":["5D3D9E24-00000-000004"],"obj_refs":{"RscDfn":"vm-106-disk-1"}}]
 at /usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm line 255.
	PVE::Storage::Custom::LINSTORPlugin::free_image("PVE::Storage::Custom::LINSTORPlugin", "drbdstorage", HASH(0x561538c03940), "vm-106-disk-1", undef, "raw") called at /usr/share/perl5/PVE/Storage.pm line 765
	PVE::Storage::__ANON__() called at /usr/share/perl5/PVE/Cluster.pm line 915
	eval {...} called at /usr/share/perl5/PVE/Cluster.pm line 883
	PVE::Cluster::__ANON__("storage-drbdstorage", undef, CODE(0x561538d6e7a0)) called at /usr/share/perl5/PVE/Cluster.pm line 954
	PVE::Cluster::cfs_lock_storage("drbdstorage", undef, CODE(0x561538d6e7a0)) called at /usr/share/perl5/PVE/Storage/Plugin.pm line 390
	PVE::Storage::Plugin::cluster_lock_storage("PVE::Storage::Custom::LINSTORPlugin", "drbdstorage", 1, undef, CODE(0x561538d6e7a0)) called at /usr/share/perl5/PVE/Storage.pm line 766
	PVE::Storage::vdisk_free(HASH(0x561538351b88), "drbdstorage:vm-106-disk-1") called at /usr/share/perl5/PVE/API2/Qemu.pm line 2942
	eval {...} called at /usr/share/perl5/PVE/API2/Qemu.pm line 2942
	PVE::API2::Qemu::__ANON__("UPID:pve3:00046101:0005F0BC:5D487A87:qmclone:101:root\@pam:") called at /usr/share/perl5/PVE/RESTEnvironment.pm line 610
	eval {...} called at /usr/share/perl5/PVE/RESTEnvironment.pm line 601
	PVE::RESTEnvironment::fork_worker(PVE::RPCEnvironment=HASH(0x561538b80250), "qmclone", 101, "root\@pam", CODE(0x561538361928)) called at /usr/share/perl5/PVE/API2/Qemu.pm line 2953
	PVE::API2::Qemu::__ANON__() called at /usr/share/perl5/PVE/Tools.pm line 201
	eval {...} called at /usr/share/perl5/PVE/Tools.pm line 201
	PVE::Tools::lock_file_full("/var/lock/qemu-server/lock-106.conf", 1, 0, CODE(0x561538be0ba8)) called at /usr/share/perl5/PVE/Tools.pm line 210
	PVE::Tools::lock_file("/var/lock/qemu-server/lock-106.conf", 1, CODE(0x561538be0ba8)) called at /usr/share/perl5/PVE/AbstractConfig.pm line 78
	PVE::AbstractConfig::lock_config_full("PVE::QemuConfig", 106, 1, CODE(0x561538be0ba8)) called at /usr/share/perl5/PVE/API2/Qemu.pm line 2958
	PVE::API2::Qemu::__ANON__() called at /usr/share/perl5/PVE/Tools.pm line 201
	eval {...} called at /usr/share/perl5/PVE/Tools.pm line 201
	PVE::Tools::lock_file_full("/var/lock/qemu-server/lock-101.conf", 1, 1, CODE(0x561538d55560)) called at /usr/share/perl5/PVE/AbstractConfig.pm line 106
	PVE::AbstractConfig::lock_config_mode("PVE::QemuConfig", 101, 1, 1, CODE(0x561538d55560)) called at /usr/share/perl5/PVE/API2/Qemu.pm line 2959
	PVE::API2::Qemu::__ANON__(HASH(0x561538d58388)) called at /usr/share/perl5/PVE/RESTHandler.pm line 446
	PVE::RESTHandler::handle("PVE::API2::Qemu", HASH(0x561536dd3120), HASH(0x561538d58388)) called at /usr/share/perl5/PVE/HTTPServer.pm line 167
	eval {...} called at /usr/share/perl5/PVE/HTTPServer.pm line 133
	PVE::HTTPServer::rest_handler(PVE::HTTPServer=HASH(0x561532571538), "10.1.2.12", "POST", "/nodes/pve3/qemu/101/clone", HASH(0x561538c27f70), HASH(0x561538cf5660), "extjs") called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 712
	eval {...} called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 686
	PVE::APIServer::AnyEvent::handle_api2_request(PVE::HTTPServer=HASH(0x561532571538), HASH(0x561538d58a18), HASH(0x561538c27f70), "POST", "/api2/extjs/nodes/pve3/qemu/101/clone") called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 939
	eval {...} called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 931
	PVE::APIServer::AnyEvent::handle_request(PVE::HTTPServer=HASH(0x561532571538), HASH(0x561538d58a18), HASH(0x561538c27f70), "POST", "/api2/extjs/nodes/pve3/qemu/101/clone") called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 1325
	PVE::APIServer::AnyEvent::__ANON__(AnyEvent::Handle=HASH(0x561538c89848), "name=dfdfddf34\x{26}full=1\x{26}newid=106\x{26}target=pve3") called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent/Handle.pm line 1522
	AnyEvent::Handle::__ANON__(AnyEvent::Handle=HASH(0x561538c89848)) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent/Handle.pm line 1332
	AnyEvent::Handle::_drain_rbuf(AnyEvent::Handle=HASH(0x561538c89848)) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent/Handle.pm line 2032
	AnyEvent::Handle::__ANON__(EV::IO=SCALAR(0x561538d5d4e0), 1) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent/Impl/EV.pm line 88
	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent/Impl/EV.pm line 88
	AnyEvent::CondVar::Base::_wait(AnyEvent::CondVar=HASH(0x561538342b60)) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent.pm line 2026
	AnyEvent::CondVar::Base::recv(AnyEvent::CondVar=HASH(0x561538342b60)) called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 1612
	PVE::APIServer::AnyEvent::run(PVE::HTTPServer=HASH(0x561532571538)) called at /usr/share/perl5/PVE/Service/pvedaemon.pm line 52
	PVE::Service::pvedaemon::run(PVE::Service::pvedaemon=HASH(0x561538b7a740)) called at /usr/share/perl5/PVE/Daemon.pm line 171
	eval {...} called at /usr/share/perl5/PVE/Daemon.pm line 171
	PVE::Daemon::__ANON__(PVE::Service::pvedaemon=HASH(0x561538b7a740)) called at /usr/share/perl5/PVE/Daemon.pm line 391
	eval {...} called at /usr/share/perl5/PVE/Daemon.pm line 380
	PVE::Daemon::__ANON__(PVE::Service::pvedaemon=HASH(0x561538b7a740), undef) called at /usr/share/perl5/PVE/Daemon.pm line 552
	eval {...} called at /usr/share/perl5/PVE/Daemon.pm line 550
	PVE::Daemon::start(PVE::Service::pvedaemon=HASH(0x561538b7a740), undef) called at /usr/share/perl5/PVE/Daemon.pm line 661
	PVE::Daemon::__ANON__(HASH(0x561532551410)) called at /usr/share/perl5/PVE/RESTHandler.pm line 446
	PVE::RESTHandler::handle("PVE::Service::pvedaemon", HASH(0x56153256b670), HASH(0x561532551410)) called at /usr/share/perl5/PVE/RESTHandler.pm line 855
	eval {...} called at /usr/share/perl5/PVE/RESTHandler.pm line 838
	PVE::RESTHandler::cli_handler("PVE::Service::pvedaemon", "pvedaemon start", "start", ARRAY(0x5615328103a0), ARRAY(0x56153256bce8), undef, undef, undef) called at /usr/share/perl5/PVE/CLIHandler.pm line 580
	PVE::CLIHandler::__ANON__(ARRAY(0x561532551638), CODE(0x5615327d11a8), undef) called at /usr/share/perl5/PVE/CLIHandler.pm line 657
	PVE::CLIHandler::run_cli_handler("PVE::Service::pvedaemon", "prepare", CODE(0x5615327d11a8)) called at /usr/bin/pvedaemon line 27
TASK ERROR: clone failed: copy failed: command '/usr/bin/qemu-img convert -p -n -f raw -O raw /dev/drbd/by-res/vm-101-disk-1/0 /dev/drbd/by-res/vm-106-disk-1/0' failed: interrupted by signal
```

**Comment by rck** [comment]
> ```
> create full clone of drive scsi0 (drbdstorage:vm-101-disk-1)
> transferred: 0 bytes remaining: 10737418240 bytes total: 10737418240 bytes progression: 0.00 %
> transferred: 109521666 bytes remaining: 10627896574 bytes total: 10737418240 bytes progression: 1.02 %
> transferred: 217969590 bytes remaining: 10519448650 bytes total: 10737418240 bytes progression: 2.03 %
> transferred: 327491256 bytes remaining: 10409926984 bytes total: 10737418240 bytes progression: 3.05 %
> transferred: 435939180 bytes remaining: 10301479060 bytes total: 10737418240 bytes progression: 4.06 %
> transferred: 545460846 bytes remaining: 10191957394 bytes total: 10737418240 bytes progression: 5.08 %
> transferred: 653908770 bytes remaining: 10083509470 bytes total: 10737418240 bytes progression: 6.09 %
> transferred: 763430436 bytes remaining: 9973987804 bytes total: 10737418240 bytes progression: 7.11 %
> transferred: 871878361 bytes remaining: 9865539879 bytes total: 10737418240 bytes progression: 8.12 %
> transferred: 981400027 bytes remaining: 9756018213 bytes total: 10737418240 bytes progression: 9.14 %
> transferred: 1090921693 bytes remaining: 9646496547 bytes total: 10737418240 bytes progression: 10.16 %
> transferred: 1199369617 bytes remaining: 9538048623 bytes total: 10737418240 bytes progression: 11.17 %
> transferred: 1308891283 bytes remaining: 9428526957 bytes total: 10737418240 bytes progression: 12.19 %
> transferred: 1417339207 bytes remaining: 9320079033 bytes total: 10737418240 bytes progression: 13.20 %
> transferred: 1526860873 bytes remaining: 9210557367 bytes total: 10737418240 bytes progression: 14.22 %
> transferred: 1635308797 bytes remaining: 9102109443 bytes total: 10737418240 bytes progression: 15.23 %
> transferred: 1744830464 bytes remaining: 8992587776 bytes total: 10737418240 bytes progression: 16.25 %
> error with cfs lock 'storage-drbdstorage': Could not delete resource vm-106-disk-1, because:
> [{"ret_code":-4611686018373385243,"message":"Resource 'vm-106-disk-1' on node 'pve3' is still in use.","cause":"Resource is mounted/in use.","correction":"Un-mount resource 'vm-106-disk-1' on the node 'pve3'.","details":"Resource definition: vm-106-disk-1","error_report_ids":["5D3D9E24-00000-000004"],"obj_refs":{"RscDfn":"vm-106-disk-1"}}]
>  at /usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm line 255.
> ```

Okay, that is an interesting one. From this report we see it happens in line 255 in free_image(), which is a pretty simple function. It used to call `linstor resource-definition delete`, and now directly does the equivalent REST call. There never has been any extra logic that made this work.

So:
- Can you reproduce it?
- If so, does adding a `sleep(10);` at line 253 help?

Because my guess is: A "resource-definition delete" uses a cached "in use" flag on the controller, it does not hit the satellite if the controller thinks it is in use! So I think this is a race where qemu (from the clone action) had the DRBD device open, the controller knew that state because the satellite told it so, qemu dies/gets killed because of your cancel action and actually closes the DRBD device, which becomes secondary. But then the plugin immediately makes the delete call while the satellite did not have the chance to tell the controller that the resource is now already secondary. Typical race, and maybe getting the Python client to start was previously long enough that the satellite could tell the controller. You then could delete it without making the resource secondary, right?

**Comment by acidrop** [comment]
> * Can you reproduce it?

Yes, tried cloning a different vm this time, same result. 

log:
===
`create full clone of drive scsi0 (drbdstorage:vm-103-disk-1)
transferred: 0 bytes remaining: 15029137408 bytes total: 15029137408 bytes progression: 0.00 %
transferred: 150291374 bytes remaining: 14878846034 bytes total: 15029137408 bytes progression: 1.00 %
transferred: 302085661 bytes remaining: 14727051747 bytes total: 15029137408 bytes progression: 2.01 %
transferred: 452377035 bytes remaining: 14576760373 bytes total: 15029137408 bytes progression: 3.01 %
transferred: 604171323 bytes remaining: 14424966085 bytes total: 15029137408 bytes progression: 4.02 %
transferred: 754462697 bytes remaining: 14274674711 bytes total: 15029137408 bytes progression: 5.02 %
error with cfs lock 'storage-drbdstorage': Could not delete resource vm-106-disk-1, because:
[{"ret_code":-4611686018373385243,"message":"Resource 'vm-106-disk-1' on node 'pve3' is still in use.","cause":"Resource is mounted/in use.","correction":"Un-mount resource 'vm-106-disk-1' on the node 'pve3'.","details":"Resource definition: vm-106-disk-1","error_report_ids":["5D492910-00000-000002"],"obj_refs":{"RscDfn":"vm-106-disk-1"}}]
 at /usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm line 254.
	PVE::Storage::Custom::LINSTORPlugin::free_image("PVE::Storage::Custom::LINSTORPlugin", "drbdstorage", HASH(0x5601781a2ea0), "vm-106-disk-1", undef, "raw") called at /usr/share/perl5/PVE/Storage.pm line 765
	PVE::Storage::__ANON__() called at /usr/share/perl5/PVE/Cluster.pm line 915
	eval {...} called at /usr/share/perl5/PVE/Cluster.pm line 883
	PVE::Cluster::__ANON__("storage-drbdstorage", undef, CODE(0x5601782ad218)) called at /usr/share/perl5/PVE/Cluster.pm line 954
	PVE::Cluster::cfs_lock_storage("drbdstorage", undef, CODE(0x5601782ad218)) called at /usr/share/perl5/PVE/Storage/Plugin.pm line 390
	PVE::Storage::Plugin::cluster_lock_storage("PVE::Storage::Custom::LINSTORPlugin", "drbdstorage", 1, undef, CODE(0x5601782ad218)) called at /usr/share/perl5/PVE/Storage.pm line 766
	PVE::Storage::vdisk_free(HASH(0x56017814ce28), "drbdstorage:vm-106-disk-1") called at /usr/share/perl5/PVE/API2/Qemu.pm line 2942
	eval {...} called at /usr/share/perl5/PVE/API2/Qemu.pm line 2942
	PVE::API2::Qemu::__ANON__("UPID:pve3:00122714:00912156:5D49DEDA:qmclone:103:root\@pam:") called at /usr/share/perl5/PVE/RESTEnvironment.pm line 610
	eval {...} called at /usr/share/perl5/PVE/RESTEnvironment.pm line 601
	PVE::RESTEnvironment::fork_worker(PVE::RPCEnvironment=HASH(0x5601780967d8), "qmclone", 103, "root\@pam", CODE(0x5601780a82b0)) called at /usr/share/perl5/PVE/API2/Qemu.pm line 2953
	PVE::API2::Qemu::__ANON__() called at /usr/share/perl5/PVE/Tools.pm line 201
	eval {...} called at /usr/share/perl5/PVE/Tools.pm line 201
	PVE::Tools::lock_file_full("/var/lock/qemu-server/lock-106.conf", 1, 0, CODE(0x560178277b70)) called at /usr/share/perl5/PVE/Tools.pm line 210
	PVE::Tools::lock_file("/var/lock/qemu-server/lock-106.conf", 1, CODE(0x560178277b70)) called at /usr/share/perl5/PVE/AbstractConfig.pm line 78
	PVE::AbstractConfig::lock_config_full("PVE::QemuConfig", 106, 1, CODE(0x560178277b70)) called at /usr/share/perl5/PVE/API2/Qemu.pm line 2958
	PVE::API2::Qemu::__ANON__() called at /usr/share/perl5/PVE/Tools.pm line 201
	eval {...} called at /usr/share/perl5/PVE/Tools.pm line 201
	PVE::Tools::lock_file_full("/var/lock/qemu-server/lock-103.conf", 1, 1, CODE(0x56017814ccf0)) called at /usr/share/perl5/PVE/AbstractConfig.pm line 106
	PVE::AbstractConfig::lock_config_mode("PVE::QemuConfig", 103, 1, 1, CODE(0x56017814ccf0)) called at /usr/share/perl5/PVE/API2/Qemu.pm line 2959
	PVE::API2::Qemu::__ANON__(HASH(0x560178220aa0)) called at /usr/share/perl5/PVE/RESTHandler.pm line 446
	PVE::RESTHandler::handle("PVE::API2::Qemu", HASH(0x5601762e97c0), HASH(0x560178220aa0)) called at /usr/share/perl5/PVE/HTTPServer.pm line 167
	eval {...} called at /usr/share/perl5/PVE/HTTPServer.pm line 133
	PVE::HTTPServer::rest_handler(PVE::HTTPServer=HASH(0x560171a88538), "10.1.2.12", "POST", "/nodes/pve3/qemu/103/clone", HASH(0x560178262208), HASH(0x560178272f78), "extjs") called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 712
	eval {...} called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 686
	PVE::APIServer::AnyEvent::handle_api2_request(PVE::HTTPServer=HASH(0x560171a88538), HASH(0x560171a88700), HASH(0x560178262208), "POST", "/api2/extjs/nodes/pve3/qemu/103/clone") called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 939
	eval {...} called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 931
	PVE::APIServer::AnyEvent::handle_request(PVE::HTTPServer=HASH(0x560171a88538), HASH(0x560171a88700), HASH(0x560178262208), "POST", "/api2/extjs/nodes/pve3/qemu/103/clone") called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 1325
	PVE::APIServer::AnyEvent::__ANON__(AnyEvent::Handle=HASH(0x5601780f6a38), "full=1\x{26}newid=106\x{26}storage=drbdstorage\x{26}target=pve3\x{26}name=dasdsa") called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent/Handle.pm line 1522
	AnyEvent::Handle::__ANON__(AnyEvent::Handle=HASH(0x5601780f6a38)) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent/Handle.pm line 1332
	AnyEvent::Handle::_drain_rbuf(AnyEvent::Handle=HASH(0x5601780f6a38)) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent/Handle.pm line 2032
	AnyEvent::Handle::__ANON__(EV::IO=SCALAR(0x56017814cbd0), 1) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent/Impl/EV.pm line 88
	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent/Impl/EV.pm line 88
	AnyEvent::CondVar::Base::_wait(AnyEvent::CondVar=HASH(0x560177859160)) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/AnyEvent.pm line 2026
	AnyEvent::CondVar::Base::recv(AnyEvent::CondVar=HASH(0x560177859160)) called at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 1612
	PVE::APIServer::AnyEvent::run(PVE::HTTPServer=HASH(0x560171a88538)) called at /usr/share/perl5/PVE/Service/pvedaemon.pm line 52
	PVE::Service::pvedaemon::run(PVE::Service::pvedaemon=HASH(0x560178090d10)) called at /usr/share/perl5/PVE/Daemon.pm line 171
	eval {...} called at /usr/share/perl5/PVE/Daemon.pm line 171
	PVE::Daemon::__ANON__(PVE::Service::pvedaemon=HASH(0x560178090d10)) called at /usr/share/perl5/PVE/Daemon.pm line 391
	eval {...} called at /usr/share/perl5/PVE/Daemon.pm line 380
	PVE::Daemon::__ANON__(PVE::Service::pvedaemon=HASH(0x560178090d10), undef) called at /usr/share/perl5/PVE/Daemon.pm line 552
	eval {...} called at /usr/share/perl5/PVE/Daemon.pm line 550
	PVE::Daemon::start(PVE::Service::pvedaemon=HASH(0x560178090d10), undef) called at /usr/share/perl5/PVE/Daemon.pm line 661
	PVE::Daemon::__ANON__(HASH(0x560171a68420)) called at /usr/share/perl5/PVE/RESTHandler.pm line 446
	PVE::RESTHandler::handle("PVE::Service::pvedaemon", HASH(0x560171a82680), HASH(0x560171a68420)) called at /usr/share/perl5/PVE/RESTHandler.pm line 855
	eval {...} called at /usr/share/perl5/PVE/RESTHandler.pm line 838
	PVE::RESTHandler::cli_handler("PVE::Service::pvedaemon", "pvedaemon start", "start", ARRAY(0x560171d27448), ARRAY(0x560171a82cf8), undef, undef, undef) called at /usr/share/perl5/PVE/CLIHandler.pm line 580
	PVE::CLIHandler::__ANON__(ARRAY(0x560171a68648), CODE(0x560171ce8208), undef) called at /usr/share/perl5/PVE/CLIHandler.pm line 657
	PVE::CLIHandler::run_cli_handler("PVE::Service::pvedaemon", "prepare", CODE(0x560171ce8208)) called at /usr/bin/pvedaemon line 27
TASK ERROR: clone failed: copy failed: command '/usr/bin/qemu-img convert -p -n -f raw -O raw /dev/drbd/by-res/vm-103-disk-1/0 /dev/drbd/by-res/vm-106-disk-1/0' failed: interrupted by signal
`

> * If so, does adding a `sleep(10);` at line 253 help?

Doesn't seem to help. After stopping cloning operation, it stays there forever...nothing happens no matter how long you wait.

log:
===
create full clone of drive scsi0 (drbdstorage:vm-103-disk-1)
transferred: 0 bytes remaining: 15029137408 bytes total: 15029137408 bytes progression: 0.00 %
transferred: 150291374 bytes remaining: 14878846034 bytes total: 15029137408 bytes progression: 1.00 %
transferred: 302085661 bytes remaining: 14727051747 bytes total: 15029137408 bytes progression: 2.01 %
transferred: 452377035 bytes remaining: 14576760373 bytes total: 15029137408 bytes progression: 3.01 %

**Comment by rck** [comment]
I added some polling code in rc2. I don't see how overall that would be better than the sleep, but please try again. Make sure that the `pvedaemon` was restarted.

**Comment by acidrop** [comment]
Installed rc2 and restarted pvedaemon on all (3) nodes, but had same behavior as when setting sleep(10); ...

Perhaps it's better to close this as it may be a corner case as you said. This is not a physical cluster by the way, but 3 virtualized PVE nodes, which I use for testing, so the results might not reflect to the real world scenarios..

**Comment by rck** [comment]
It is a weird case and I don't know what the plugin could do besides what it already does. So yes, I agree, let's discard that, I will keep it in mind.
