### ISSUE TITLE
Migrate button in gui takes too long to become available

### ISSUE THREAD

**Issue by acidrop** [LINBIT/linstor-proxmox#24]
- PVE6
- Latest linstor proxmox-plugin (4.0.0~rc2-1) , linstor packages

Select an arbitrary VM and then click on migrate option in GUI. Migrate button takes approximately 17 seconds to become available (become blue). This is true both for offline and online migrations.

Using 'qm migrate' command in CLI for the same task works as expected (fast).

Might be a race condition, but was able to reproduce it repeatedly in my test environment (reduce sleep time?).

**Comment by rck** [comment]
You are a reservoir for curios bugs :-D. Anybody else seen that? I, FWIW, have seen that 0 times while testing the plugin (I test GUI-only). But it might vary with the number of resources. It might vary because LVM is not configured correctly and LINSTOR takes long to list stuff. Is LINSTOR (like listing voluemes/resources fast at these points in time?). It could be that Proxmox asks the same questions over and over and over again. They even provide a cache for plugins, because they loop over the same thing again and again. From what I see, I use the cache the same as it was used previously. Does that happen once (e.g., on startup), or again and again?

**Comment by acidrop** [comment]
:-) that's true... I'm testing this on 3 virtualized pve nodes and I'm using zfs as linstor storage pool backend. I did not had this behaviour previously when in PVE5, it started once I upgraded to 6. It was during this time that I also upgraded linstor components to 1.0.1-1.
I have only 3 VMs on this cluster, one of them it serves as linstor controller appliance, so in general the cluster is idle.
It appears that listing linstor volumes it takes almost same time as it takes to the migrate button to become available, so yes it may be a co-relation between them...Not sure why it takes so long, I have rebooted all (3) nodes and the controller VM and there's nothing wrong in the logs. 
It's only when issuing "linstor r l" that it takes approx 20sec to show results, while rest of commands complete quite fast.

**Comment by rck** [comment]
Then we have a winner, and I'm glad it is not me :).

That would be the time I usually shout "misconfigured LVM!", but... Is zfs listing during that time also slow? `zfs list` speed during that time would be interesting or `zfs get all`, do they feel okay or are they slow as well? ZFS can be very RAM hungry, and as this is virtual, maybe that is the actual bottleneck?

**Comment by acidrop** [comment]
Ok, I've dug a bit deeper... :-)

-Downgraded linstor packages to previous versions (linstor-satellite=0.9.13-1 linstor-common=0.9.13-1 linstor-client=0.9.9-1  linstor-controller=0.9.13-1) ==> result was the same.
-Downgraded linstor-proxmox to the repo version ==> result was the same.
-Hard resetting (reboot -f) controller VM  fixes the problem initially, but then after some time it comes back again. A normal reboot or linstor-controller.service restart does not help. Can't explain this. Did a fsck inside VM filesystem but there were no inconsistencies.

These are the times when the problem is present:
=====================================
`root@drbd-controller:/var/lib/linstor# time linstor r l > /dev/null
real	0m22.185s
user	0m0.232s
sys	0m0.044s
root@drbd-controller:/var/lib/linstor# time linstor r l > /dev/null
real	0m18.865s
user	0m0.244s
sys	0m0.048s
root@drbd-controller:/var/lib/linstor# time linstor r l > /dev/null
real	0m27.489s
user	0m0.232s
sys	0m0.096s
`
Listing zfs volumes/properties is always fast(on all nodes):
============================================
`root@pve1:~# time zfs list drbdpool > /dev/null
real	0m0.014s
user	0m0.004s
sys	0m0.010s
root@pve1:~# time zfs list drbdpool > /dev/null
real	0m0.022s
user	0m0.004s
sys	0m0.018s
root@pve1:~# time zfs list drbdpool > /dev/null
real	0m0.013s
user	0m0.000s
sys	0m0.013s`

`root@pve1:~# time zfs get all drbdpool > /dev/null
real	0m0.015s
user	0m0.006s
sys	0m0.010s
root@pve1:~# time zfs get all drbdpool > /dev/null
real	0m0.012s
user	0m0.005s
sys	0m0.007s
root@pve1:~# time zfs get all drbdpool > /dev/null
real	0m0.013s
user	0m0.005s
sys	0m0.008s`

There's enough memory to support zfs pools even though this is a virtualized setup (and this same setup was working fine before upgrading to pve6 anyways):
===============================================
`root@pve1:~# zpool list
NAME       SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
drbdpool  79.5G  26.8G  52.7G        -         -    34%    33%  1.00x    ONLINE  -
`
`root@pve1:~# free -m
              total        used        free      shared  buff/cache   available
Mem:           7973        2366        4737          71         868        5266
Swap:          2431           0        2431
`
linstor-controller.service logs:
======================
`root@drbd-controller:~# journalctl -u linstor-controller
-- Logs begin at Sun 2019-08-11 15:13:06 BST, end at Sun 2019-08-11 15:17:01 BST. --
Aug 11 15:13:09 drbd-controller systemd[1]: Started LINSTOR Controller Service.
Aug 11 15:13:13 drbd-controller Controller[699]: LINSTOR, Module Controller
Aug 11 15:13:13 drbd-controller Controller[699]: Version:            1.0.1 (98a9905de43631b745c7c0741c2ef8f577513b23)
Aug 11 15:13:13 drbd-controller Controller[699]: Build time:         2019-08-09T06:50:31+00:00
Aug 11 15:13:13 drbd-controller Controller[699]: Java Version:       1.8
Aug 11 15:13:13 drbd-controller Controller[699]: Java VM:            Oracle Corporation, Version 25.222-b10
Aug 11 15:13:13 drbd-controller Controller[699]: Operating system:   Linux, Version 4.9.0-9-amd64
Aug 11 15:13:13 drbd-controller Controller[699]: Environment:        amd64, 2 processors, 241 MiB memory reserved for allocations
Aug 11 15:13:13 drbd-controller Controller[699]: System components initialization in progress
Aug 11 15:13:14 drbd-controller Controller[699]: 15:13:14.856 [main] INFO  LINSTOR/Controller - Log directory set to: '/var/log/linstor-controller'
Aug 11 15:13:15 drbd-controller Controller[699]: 15:13:15.058 [main] INFO  LINSTOR/Controller - Linstor configuration file loaded from '/etc/linstor/linstor.toml'.
Aug 11 15:13:15 drbd-controller Controller[699]: 15:13:15.060 [Main] INFO  LINSTOR/Controller - Loading API classes started.
Aug 11 15:13:16 drbd-controller Controller[699]: 15:13:16.191 [Main] INFO  LINSTOR/Controller - API classes loading finished: 1131ms
Aug 11 15:13:16 drbd-controller Controller[699]: 15:13:16.192 [Main] INFO  LINSTOR/Controller - Dependency injection started.
Aug 11 15:13:18 drbd-controller Controller[699]: 15:13:18.672 [Main] INFO  LINSTOR/Controller - Dependency injection finished: 2480ms
Aug 11 15:13:19 drbd-controller Controller[699]: 15:13:19.056 [Main] INFO  LINSTOR/Controller - Initializing authentication subsystem
Aug 11 15:13:19 drbd-controller Controller[699]: 15:13:19.628 [Main] INFO  LINSTOR/Controller - Initializing the database connection pool
Aug 11 15:13:21 drbd-controller Controller[699]: 15:13:21.103 [Main] INFO  org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 5.2.4 by Boxfuse
Aug 11 15:13:21 drbd-controller Controller[699]: 15:13:21.132 [Main] INFO  org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:h2:/var/lib/linstor/linstordb (H2 1.
Aug 11 15:13:21 drbd-controller Controller[699]: 15:13:21.404 [Main] INFO  org.flywaydb.core.internal.command.DbValidate - Successfully validated 25 migrations (execution time 00:0
Aug 11 15:13:21 drbd-controller Controller[699]: 15:13:21.472 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Current version of schema "LINSTOR": 2019.07.23.13.37
Aug 11 15:13:21 drbd-controller Controller[699]: 15:13:21.497 [Main] WARN  org.flywaydb.core.internal.command.DbMigrate - outOfOrder mode is active. Migration of schema "LINSTOR" m
Aug 11 15:13:21 drbd-controller Controller[699]: 15:13:21.501 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Schema "LINSTOR" is up to date. No migration necessary.
Aug 11 15:13:21 drbd-controller Controller[699]: 15:13:21.525 [Main] INFO  LINSTOR/Controller - Loading security objects
Aug 11 15:13:21 drbd-controller Controller[699]: 15:13:21.563 [Main] INFO  LINSTOR/Controller - Current security level is NO_SECURITY
Aug 11 15:13:21 drbd-controller Controller[699]: 15:13:21.618 [Main] INFO  LINSTOR/Controller - Core objects load from database is in progress
Aug 11 15:13:22 drbd-controller Controller[699]: 15:13:22.008 [Main] INFO  LINSTOR/Controller - Core objects load from database completed
Aug 11 15:13:22 drbd-controller Controller[699]: 15:13:22.209 [Main] INFO  LINSTOR/Controller - Starting service instance 'DatabaseService' of type DatabaseService
Aug 11 15:13:22 drbd-controller Controller[699]: 15:13:22.210 [Main] INFO  LINSTOR/Controller - Starting service instance 'GrizzlyHttpServer' of type Grizzly-HTTP-Server
Aug 11 15:13:24 drbd-controller Controller[699]: Aug 11, 2019 3:13:24 PM org.glassfish.grizzly.http.server.accesslog.FileAppender <init>
Aug 11 15:13:24 drbd-controller Controller[699]: INFO: Access log file "/var/log/linstor-controller/rest-access.log" opened
Aug 11 15:13:24 drbd-controller Controller[699]: Aug 11, 2019 3:13:24 PM org.glassfish.grizzly.http.server.NetworkListener start
Aug 11 15:13:24 drbd-controller Controller[699]: INFO: Started listener bound to [[::]:3370]
Aug 11 15:13:24 drbd-controller Controller[699]: Aug 11, 2019 3:13:24 PM org.glassfish.grizzly.http.server.HttpServer start
Aug 11 15:13:24 drbd-controller Controller[699]: INFO: [HttpServer] Started.
Aug 11 15:13:24 drbd-controller Controller[699]: 15:13:24.849 [Main] INFO  LINSTOR/Controller - Starting service instance 'TaskScheduleService' of type TaskScheduleService
Aug 11 15:13:24 drbd-controller Controller[699]: 15:13:24.850 [Main] INFO  LINSTOR/Controller - Starting service instance 'TimerEventService' of type TimerEventService
Aug 11 15:13:24 drbd-controller Controller[699]: 15:13:24.852 [Main] INFO  LINSTOR/Controller - Initializing network communications services
Aug 11 15:13:24 drbd-controller Controller[699]: 15:13:24.860 [Main] WARN  LINSTOR/Controller - The SSL network communication service 'DebugSslConnector' could not be started becau
Aug 11 15:13:24 drbd-controller Controller[699]: 15:13:24.867 [TaskScheduleService] INFO  LINSTOR/Controller - LogArchive: Running log archive on directory: /var/log/linstor-contro
Aug 11 15:13:24 drbd-controller Controller[699]: 15:13:24.880 [Main] INFO  LINSTOR/Controller - Created network communication service 'PlainConnector', bound to ::0:3376
Aug 11 15:13:24 drbd-controller Controller[699]: 15:13:24.881 [Main] WARN  LINSTOR/Controller - The SSL network communication service 'SslConnector' could not be started because th
Aug 11 15:13:24 drbd-controller Controller[699]: 15:13:24.898 [Main] INFO  LINSTOR/Controller - Reconnecting to previously known nodes
Aug 11 15:13:24 drbd-controller Controller[699]: 15:13:24.905 [TaskScheduleService] INFO  LINSTOR/Controller - LogArchive: No logs to archive.
Aug 11 15:13:24 drbd-controller Controller[699]: 15:13:24.988 [Main] INFO  LINSTOR/Controller - Reconnect requests sent
Aug 11 15:13:24 drbd-controller Controller[699]: 15:13:24.989 [Main] INFO  LINSTOR/Controller - Controller initialized`

Controller VM runs on Debian Strech - latest updates.

Below follow the times when controller vm works as expected (reboot -f):
=======================================================
`root@drbd-controller:~# time linstor r l > /dev/null
real	0m0.515s
user	0m0.216s
sys	0m0.112s
root@drbd-controller:~# time linstor r l > /dev/null
real	0m0.417s
user	0m0.212s
sys	0m0.040s
root@drbd-controller:~# time linstor r l > /dev/null
real	0m0.434s
user	0m0.224s
sys	0m0.064s`

**Comment by rck** [comment]
And at these times when it is slow, how is the load in the controller VM? Is it overloaded? And if so, who is it? LINSTOR/JVM?

**Comment by acidrop** [comment]
No, it's not overloaded at all. Actually I'm now having only the controller VM running in the pve6 cluster, all other VMs are stopped and still the output of 'linstor r l' take too long...

> root@drbd-controller:~# vmstat 1 -w
> procs -----------------------memory---------------------- ---swap-- -----io---- -system-- --------cpu--------
>  r  b         swpd         free         buff        cache   si   so    bi    bo   in   cs  us  sy  id  wa  st
>  3  0            0       586212        52756       165312    0    0     2     1   37   60   0   0  99   0   0
>  0  0            0       586252        52756       165312    0    0     0     0   74  121   0   0  99   0   1
>  0  0            0       586128        52756       165312    0    0     0    24   70  115   0   1  99   0   0
>  0  0            0       586192        52756       165312    0    0     0     0  135  189   2   1  97   1   0

**Comment by rp-** [comment]
linstor listing can take a longer time if the satellites devicemanager is currently in a run, and some command takes longer.
Satellite log output would be interesting with DEBUG logging to identify the external command that takes so long.

**Comment by acidrop** [comment]
Attaching logs,hope I did it the right way...I executed 'linstor r l' multiple times during this session.

[pve1_satellite_log](https://gist.github.com/acidrop/f9881083cbf0b937689285605043d8cd)
[pve2_satellite_log](https://gist.github.com/acidrop/50bac7c18cb69cf9e40193d001e3d602)
[pve3_satellite_log](https://gist.github.com/acidrop/39617830d490e9dfb61c8255b4b8d205)
[linstor-controller_log](https://gist.github.com/acidrop/bb3929cf671c3546a8a8dac159b8df64)

**Comment by acidrop** [comment]
Managed to locate the problem. It occurred due to having 2 separate networks (1 for drbd traffic and 1 for satellite communication). Once I merged both to a single network the response time in the gui and cli was fast.
