### ISSUE TITLE
Can't move VM

### ISSUE THREAD

**Issue by smaurin** [LINBIT/linstor-proxmox#27]
Hello,

When I try to move a VM promox send me an error : 

```
2019-09-25 11:16:53 starting migration of VM 416 to node 'pves2v1' (192.168.0.205)
2019-09-25 11:16:53 ERROR: Failed to sync data - storage 'zpools1' is not available on node 'pves2v1'
2019-09-25 11:16:53 aborting phase 1 - cleanup resources
2019-09-25 11:16:53 ERROR: migration aborted (duration 00:00:01): Failed to sync data - storage 'zpools1' is not available on node 'pves2v1'
TASK ERROR: migration aborted
```

I aim to use ZFS under DRBD for thinprovisionning and compression, as well versatility of zpool usage for other needs inside my proxmox cluster. So did my installation with :

Step A add a promox vm with linstor-controler
```
# for HOSTPVE in pves1v2 pves2v1 pves3v1 pves4v1 ; do ssh -t $HOSTPVE 'hostname ; echo "options kvm-intel nested=Y" > /etc/modprobe.d/kvm-intel.conf' ; done
```
VM 100 creation as pvedrbd and add brick as 'linstor-controller' inside with https://docs.linbit.com/docs/users-guide-9.0/#ch-proxmox-linstor%7CSource
Add linstor satellite functionnality+linstor proxmox to hardware nodes.

Step B Set nodes settings
```
 for HOSTPVE in pves1v2 pves2v1 pves3v1 pves4v1 pvedrbd ; do ssh -t $HOSTPVE 'hostname ; echo -ne "[global]\ncontrollers=pvedrbd.isc.cnrs.fr\n" >>/etc/linstor/linstor-client.conf 
```

Step C nodes creation :
```
 linstor node create pves1v2 192.168.100.241
 linstor node create pves2v1 192.168.100.242
 linstor node create pves3v1 192.168.100.237
 linstor node create pves4v1 192.168.100.238
```

Step D put storage-pool DRBD over pool ZFS :
```
 linstor storage-pool create zfsthin pves1v2 zfsthin_ssd zpools1
 linstor storage-pool create zfsthin pves2v1 zfsthin_ssd zpools2
 linstor storage-pool create zfsthin pves3v1 zfsthin_hdd zpools3
 linstor storage-pool create zfsthin pves4v1 zfsthin_hdd zpools4
```

Sted E define proxmox storage :

```
cat >>/etc/pve/storage.cfg <<EOF_storage.cfg
drbd: zfsthin_ssd
	nodes pves1v2,pves2v1
	content images,rootdir
	redundancy 2
	storagepool zfsthin_ssd
	controller 192.168.100.240
	controllervm 100

drbd: zfsthin_hdd
	nodes pves3v1,pves4v1
	content images,rootdir
	redundancy 2
	storagepool zfsthin_hdd
	controller 192.168.100.240
	controllervm 100

EOF_storage.cfg
```

I suppose that "Failed to sync data - storage 'zpools1' is not available on node" is an indication that I need to share a same zpool name, but then I have difficulties with linstor strorage pool create command.

May be a problem ?

Sylvain

**Comment by rck** [comment]
At a first glance it looks this error is from Proxmox itself, LINSTOR did not get contacted for the migration. Did you configure ZFS in Proxmox? If so, maybe that confuses the whole thing.

**Comment by smaurin** [comment]
You got it, thank's a lot !
