### ISSUE TITLE
INFO: file /etc/pve/storage.cfg line 13 (section 'drbdsecondary') - unable to parse value of 'resourcegroup': unexpected property 'resourcegroup'

### ISSUE THREAD

**Issue by SoftNotWork** [LINBIT/linstor-proxmox#28]
The documentation and mailing list entries show us needing to use this to control multiple pools in one storage configuration.

$ linstor resource-group list
+--------------------------------------------------------------+
| ResourceGroup | SelectFilter          | VlmNrs | Description |
|==============================================================|
| DfltRscGrp    |                       |        |             |
|--------------------------------------------------------------|
| drbdsecondary       | PlaceCount: 4         |        |             |
|               | StoragePool: drbdsecondary  |        |             |
|--------------------------------------------------------------|
| drbdprimary     | PlaceCount: 4         |        |             |
|               | StoragePool: drbdprimary|        |             |
+--------------------------------------------------------------+

The storage section looks like:

drbd: drbdsecondary
        content rootdir,images
        controller 192.168.1.15
	resourcegroup drbdsecondary
        controllervm 100

Any ideas on what I'm doing wrong?

**Comment by rck** [comment]
And what was wrong? A too old version of the plugin?

It would be very kind if you could at least tell others how you fixed it, maybe other users run in the same problem.

I think that is not too much to ask for. If you expect help from us, give back at least a little bit, how about that?

**Comment by SoftNotWork** [comment]
Yes, the plugin version was too old on install. Update and reboot fixed it.
