### ISSUE TITLE
KVM VM HA instructions fail at enabling DRBD service

### ISSUE THREAD

**Issue by SoftNotWork** [LINBIT/linstor-proxmox#29]
The systemctl enable drbd step located here: https://docs.linbit.com/docs/linstor-guide/#s-proxmox-ls-HA

fails with the following error:

systemctl enable drbd
Synchronizing state of drbd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable drbd
update-rc.d: error: drbd Default-Start contains no runlevels, aborting.

The following package versions are installed onto the latest Proxmox:

dpkg --list|grep drbd
ii  drbd-dkms                            9.0.21-1                    all          RAID 1 over TCP/IP for Linux module source
ii  drbd-utils                           9.11.0-1                    amd64        RAID 1 over TCP/IP for Linux (user utilities)

Any ideas where we're getting it wrong?

**Comment by rck** [comment]
This was [changed](https://github.com/LINBIT/drbd-utils/commit/548749e59f8a789bb82cf30cb8d4bfb0f5373ea6#diff-d21b0dbe776759f996aca1dbae1af33b) some time ago. If you want to go that route, you can enable the `Default-Start`s again. IIRC so far this was a warning (or an error one can ignore as the service is still "systemd enabled" afterwards). So I would check if the service is actually enabled and executed after a reboot.

**Comment by SoftNotWork** [comment]
root@serv1:~# systemctl status drbd.service
● drbd.service - DRBD -- please disable. Unless you are NOT using a cluster manager.
   Loaded: loaded (/lib/systemd/system/drbd.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

If we compare that to SSH:

● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-01-27 15:26:30 PST; 56min ago

Is this how it should be responding to the systemctl enable? It doesn't appear to be starting.

**Comment by Elbandi** [comment]
You can enable the drbd.service without and sysv "hack":

    SYSTEMCTL_SKIP_SYSV=1 systemctl enable drbd

**Comment by thisisvivek** [comment]
Its wokring for me...but is it the correct way to start the service on boot?

**Comment by rck** [comment]
linstor controller HA was simplified and reworked as documented here:
https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-linstor_ha

It does no longer need the drbd.service.
