### ISSUE TITLE
APIVER 6

### ISSUE THREAD

**Issue by ggzengel** [LINBIT/linstor-proxmox#33]
The API is pushed to version 6:
> Plugin "PVE::Storage::Custom::LINSTORPlugin" is implementing an older storage API, an upgrade is recommended

Here are all changes for 5 and 6:
https://git.proxmox.com/?p=pve-storage.git;a=blobdiff;f=PVE/Storage.pm;h=4a60615926145f81077e3e4a8b428c2aebedb9ca;hp=7b285da39241f60e3a0a84bfef57e3a010c7cdcb;hb=HEAD;hpb=dc3655a1a5b4ba60dd8b6d7ce487406b644e648d

**Comment by rck** [comment]
fixed with https://github.com/LINBIT/linstor-proxmox/commit/49f446491bac60fd92a2c8713f84448119a4fb8c

this will be in the repos soon (maybe tomorrow). If not till the end of the week, feel free to ping me.
