### ISSUE TITLE
API version 7

### ISSUE THREAD

**Issue by velifico** [LINBIT/linstor-proxmox#35]
_Plugin "PVE::Storage::Custom::LINSTORPlugin" is implementing an older storage API, an upgrade is recommended_

PVE storage API version change once again. Maybe related to the release of Proxmox Backup Server 1.0.

**Comment by rck** [comment]
Thanks, I will look into it on Monday. Usually that is just a warning and the old version works just fine.

**Comment by rck** [comment]
Took a bit longer, but the latest release https://github.com/LINBIT/linstor-proxmox/commit/5dc7944365dc0a67240a67742646b8e2d057fb6b should "fix" that. Packages will be available soon
