### ISSUE TITLE
can't move VHD out of DRBD while migrating VM

### ISSUE THREAD

**Issue by ggzengel** [LINBIT/linstor-proxmox#36]
If you have 3 Proxmox, two with DRBD (px1+px2) and one with local storage (px3),
it is not possible to migrate a VM from px1 to px3.

It always says "there is no drbd" on px3. I tried it all the ways - online and offline.

Is this a Proxmox problem or Linstor plugin problem?

**Comment by acidrop** [comment]
DRBD and Linstor Satellite must be installed on _all_ nodes if you want to be able to live migrate VMs around them. Linstor will then configure the 3rd node as a "diskless" node feeding the data from the other 2 nodes.

**Comment by rck** [comment]
@ggzengel I'm not sure if I understood your use case: pxe3 has *only* local storage? no DRBD at all? How does the `storage.cfg` look like?

**Comment by ggzengel** [comment]
Meanwhile I did a test with NFS, too.
If it's a shared medium, but not at the destination, Proxmox will never move this disk like a local disk.
local => local works but not shared (nodes px4,px3) => local (px1).
Same like drbd (nodes px4,px3) => drbd (nodes px1,px2).

I reported this to Proxmox:
https://bugzilla.proxmox.com/show_bug.cgi?id=3229
