### ISSUE TITLE
Storage pool error with multiple storage pools in resource group

### ISSUE THREAD

**Issue by lukas2511** [LINBIT/linstor-proxmox#39]
Hi,

I'm currently playing around with linstor and this proxmox-plugin, and I've encountered a weird error message.

As far as i underfstand linstor allows defining and balancing over multiple storage pools per resource group (e.g. `linstor rg create --storage-pool pool1 pool2 --place-count 2 rg-name`), doing that results in `pvesm status` to print the following error message:

"Have resource group, but storage pool is undefined for resource group pool at /usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm line 150"

It still seems to be working fine and actually balancing over the defined pools as I hoped for, it just has this weird error message.

**Comment by rck** [comment]
You are right. There are some assumptions in the plugin from simpler times when there was only one storage pool per RG. At a first glance these trigger only in the "list" and "status" kind of operations, but not really on the main paths that do the actual work. Unfortunately with one exception where things fix themselves. Anyways, thanks for raising that issue, this will need some internal discussion on how to fix it properly.

I'm currently busy with other projects and as it looks like at least none of our customers uses multiple pools in one RG, so this is currently not my highest priority. This might take some time till I can work on it. Consider multiple pools per RG as unsupported as of now.

**Comment by rck** [comment]
quick update: some code paths that assume a single storage pool can be simplified by using a new LINSTOR API call, but that will require a new release of LINSTOR first. So this will not be forgotten (I hope), but will at least be pending till there is a new LINSTOR release.

**Comment by rck** [comment]
fixed in https://github.com/LINBIT/linstor-proxmox/commit/099523e67aa7ffe1a121a5f13a62797db4156e64
