### ISSUE TITLE
API Version 10

### ISSUE THREAD

**Issue by MatReiKIT** [LINBIT/linstor-proxmox#46]
Hi there,

with PVE 7.1 Update the required API Version was raised to 10.
According to an Proxmox Staff Member, Version 9 is forward compatible to Version 10.
see https://forum.proxmox.com/threads/proxmox-ve-7-1-released.99847/post-430896

Thanks
Mathias

**Comment by rck** [comment]
Thanks for reporting, I saw the release notes for 7.1 today on the proxmox devel ML. I will give it a quick test tomorrow my time and then bump the plugin version (or check how to fix it).

**Comment by bk-lg** [comment]
Thank you for your fast reaction to this. I forgot to check on my dev cluster and the upgrade killed the plugin.

**Comment by ArturoGuerra** [comment]
Can confirm it works by just changing the api version to 10, I changed it manually in each node in my cluster and linstor is working again after restarting pvedaemon
![cY2ctwhnC5](https://user-images.githubusercontent.com/18218744/142344902-efdde84e-2434-4bb3-beb8-935bb9430a4f.png)
![gSXFmETPfR](https://user-images.githubusercontent.com/18218744/142344945-b06b0776-13da-4675-92c6-85fb4e2d3f04.png)
![ce5I3gwk7P](https://user-images.githubusercontent.com/18218744/142345243-de55e8a3-0e28-4686-9972-232dee7b72d6.png)

**Comment by bk-lg** [comment]
@ArturoGuerra I tried your change on one of my dev nodes and it worked so far. I needed to also restart pveproxy to make the changes working.

**Comment by rck** [comment]
fixed in 01344ff722c66d25da4225f177254dac7f58276b ; packages should be available soon
