### ISSUE TITLE
Proxmox storage pool stay in inactive state 

### ISSUE THREAD

**Issue by msfeghouli** [LINBIT/linstor-proxmox#48]
Hi i deployed linstor proxmox plugins on proxmox v7 
i configured succefully my pool 
```
root@wx2 ~ #  linstor rg l
╭─────────────────────────────────────────────────────────────────╮
┊ ResourceGroup   ┊ SelectFilter           ┊ VlmNrs ┊ Description ┊
╞═════════════════════════════════════════════════════════════════╡
┊ DfltRscGrp      ┊ PlaceCount: 2          ┊        ┊             ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ drbdMypoolThree ┊ PlaceCount: 2          ┊ 0,1    ┊             ┊
┊                 ┊ StoragePool(s): mypool ┊        ┊             ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ r1              ┊ PlaceCount: 1          ┊ 0      ┊             ┊
┊                 ┊ StoragePool(s): data   ┊        ┊             ┊
╰─────────────────────────────────────────────────────────────────╯

```
Proxmox storage.conf 
```
drbd: lsr1
	resourcegroup r1
	content images,rootdir
	controller sx2
	nodes wa03,wx2
	preferlocal yes
drbd: drbdstorage
   content images,rootdir
   controller sx2
   resourcegroup drbdMypoolThree
```

But still have the two proxmox pools in inactive state 
```
root@wx2 ~ #  pvesm status
Name               Type     Status           Total            Used       Available        %
backupv2            pbs     active     35986630784     26199421440      9787209344   72.80%
drbdstorage        drbd   inactive               0               0               0    0.00%
local               dir     active       262016000       111613204       150402796   42.60%
ls-nvme         lvmthin     active      1565130752          156513      1564974238    0.01%
lsr1               drbd   inactive               0               0               0    0.00%
vmraid5       glusterfs     active     11182539264      5059149048      6123390216   45.24%
wb1-backup          pbs     active     35986630784     26199421440      9787209344   72.80%
```

Please Help

**Comment by rck** [comment]
What is obviously wrong is that `resource-group` `drbdMypoolThree` has two `volume-groups` instead of one. Please delete the second. Still, that alone IMO does not explain why it is inactive. Output of `linstor sp l`?

**Comment by msfeghouli** [comment]
Hi i know don't look to the label I have two noeuds for instance so I put 2 replicas 
here it Is the output of linstor sp l 
`╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ StoragePool          ┊ Node ┊ Driver   ┊ PoolName        ┊ FreeCapacity ┊ TotalCapacity ┊ CanSnapshots ┊ State ┊ SharedName ┊
╞═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ DfltDisklessStorPool ┊ sa03 ┊ DISKLESS ┊                 ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ sx2  ┊ DISKLESS ┊                 ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ data                 ┊ sa03 ┊ LVM_THIN ┊ proxvg/proxthin ┊     1.73 TiB ┊      3.46 TiB ┊ True         ┊ Ok    ┊            ┊
┊ data                 ┊ sx2  ┊ LVM_THIN ┊ proxvg/proxthin ┊     1.46 TiB ┊      1.46 TiB ┊ True         ┊ Ok    ┊        `

**Comment by rck** [comment]
It is not about labels or replica counts. 2 `vg`s in a `rg` are **always** wrong when used with proxmox.

Anyways, you did not show me anything for "mypool" in that pretty unreadable output to begin with. So back to "data". The output is from "wx2", but that node does not even have the pool ("sa03" and "sx2" have it). Even weirder, you limit them to "sx2" which does not have it, and to "wa03", whatever that node is.

So please start with one drbd storage in a simple configuration without setting `node`; with a `rg` that has **1** `vg`. And don't expect nodes that don't have a storage pool to show it as something else than "inactive" (that might even be the key point here).

**Comment by msfeghouli** [comment]
Sorry but I explain 
sx2 and wx2 are the same node, I just added another hostname to point to different nic addresses they using two different 10G Nick ( sx2 192.168.1.122, wx2 192.168.0.122 )   connected to two switches.

```
DfltDisklessStorPool ┊ sa03 ┊ DISKLESS ┊                 ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
DfltDisklessStorPool ┊ sx2  ┊ DISKLESS ┊ 
data                 ┊ sa03 ┊ LVM_THIN ┊ proxvg/proxthin ┊     1.73 TiB ┊      3.46 TiB ┊ True         ┊ Ok    ┊ 
data                 ┊ sx2  ┊ LVM_THIN ┊ proxvg/proxthin ┊     1.46 TiB ┊      1.46 TiB ┊ True         ┊ Ok    ┊ 
```
