### ISSUE TITLE
Problem migratig proxmox 6.1 to 6.4 (and 7 as well)

### ISSUE THREAD

**Issue by jkohan0** [LINBIT/linstor-proxmox#49]
We have a cluster with Proxmox on Debian an linstor. We use lintstor to store vms on thin lvm . 
When upgraded Debian 10.x to a newer one and Proxmox from 6.1 to 6.4, first thing that happened was that we had to remove from /etc/pve/storage.cfg  the clause "redundancy" and add "resourcegroup".
Then the storage is listed in proxmox but with error. In the log there is the following
"pvedaemon[2036]: Have resource group, but storage pool is undefined for resource group DfltRscGrp at /usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm line 237."

I even tried adding property "StoragePool" to rg, but seems that´s the problem (no change). 
We went on and upgraded everything to debian 11 and proxmox 7 hoping the problem will go. But it didn´t.

I attach a file with the output of  curl -X GET http://localhost:3370/v1/view/resources   (as I saw in other issue asked for it).
[view-resources.txt](https://github.com/LINBIT/linstor-proxmox/files/8548905/view-resources.txt)

Versions: 
linstor-client     1.13.0-1
linstor-common     1.18.0-1
linstor-controller 1.18.0-1
linstor-proxmox    5.2.2-1 
linstor-satellite  1.18.0-1
Proxmox 7.1

We are quite desperate, about to try to run vms from a lvm-thin that just created. Proxmox seems to see lvs normally. hope won´t have problems runing that way. (don´t know difference between using a drbd backed lvm-thin storage vs a drbdstorage proper).

Thank you

Javier

**Comment by rck** [comment]
I think everything one needs to know is documented here: https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-proxmox-ls-upgrades-4-5

So create the necessary RGs and test if spawning resources based on the RG works on the command line (via `linstor` client). Then change the `storage.cfg` as described.

I'm pretty sure there is no general issue or bug, there have been ways to many users and customers that would have run into it months/years ago when they did the plugin upgrade. Closing this as I'm pretty sure there is no bug, still feel free to report any problems, we can re-open it at any time.
