### ISSUE TITLE
Error at live migration disk from local LVM to DRBD LVM

### ISSUE THREAD

**Issue by j0ker-222** [LINBIT/linstor-proxmox#54]
Hi
I've got few simple installations like 3 ProxMox servers with DRBD pool on them, linstor-satellite and proxmox-linstor plugin. 
And I've got problem at live migrating disk from local LVM/LVM thin to DRBD's pool based on LVM/LVM thin. But if i turn off VM then I can easily without any problems migrate. And also at the same time when I'm live migrating local LVM/LVM thin to DRBD's pool based on ZFS - all going good. 

pveversion: 
pve-manager/7.4-3/9002ab8a (running kernel: 5.15.104-1-pve)

linstor pkg version:
ii  linstor-common                       1.22.1-1                       all
ii  linstor-proxmox                      7.0.0-1                        all
ii  linstor-satellite                    1.22.1-1                       all

drbd proc:
version: 9.2.3 (api:2/proto:86-122)
GIT-hash: c142ca1280c41aee1330b980544ef276330ff6ef build by root@testiko, 2023-04-10 18:28:06
Transports (api:18): tcp (9.2.3)

part of LVM's debug log(maybe at will be helpfull):
lvcreate  --config "devices { filter=['a|/dev/sdb|','r|.*|'] }" --virtualsize 5246976k linstor_thinpool0 --thinpool thinpool0 --name vm-116-disk-1_00000
lvchange  --config "devices { filter=['a|/dev/sdb|','r|.*|'] }" -ay -K linstor_thinpool0/vm-116-disk-1_00000
pvdisplay --config "devices { filter=['r|/dev/drbd.*|','a|.*|'] }" --columns -o pv_name -S vg_name=linstor_thinpool0 --noheadings --nosuffix
lvremove  --config "devices { filter=['a|/dev/sdb|','r|.*|'] }" -f linstor_thinpool0/vm-116-disk-1_00000

Error from GUI proxmox:
create full clone of drive scsi0 (lvm_local_test:vm-116-disk-0)

NOTICE
Trying to create diskful resource (vm-116-disk-1) on (testiko).
drive mirror is starting for drive-scsi0
drive-scsi0: Cancelling block job
drive-scsi0: Done.
TASK ERROR: storage migration failed: block job (mirror) error: drive-scsi0: 'mirror' has been cancelled

**Comment by rck** [comment]
I'd assume it has something to do with different block sizes/size calculation. It pops up from time to time, and I'm happy if somebody is willing to dig deeper, but moving to DRBD usually is a one time operation and there is offline migration as a "work around". I'm afaid this will be at the bottom of my TODO list forever (or until a paying customer finds a use case which would change the order of my TODO list obviously :) ).

tl;tr: known, "won't fix" because I have too many more important things to do, happy to accept/review patches.

**Comment by j0ker-222** [comment]
got it, sounds sad. Not sure that I can fix it and give to you patch, at least now.
really, this problem affects only few clients?

**Comment by dam2k** [comment]
**I solved the problem using external metadata for DRBD on linstor**.

With internal metadata the proxmox disk (and its backing logical volume) is different in size (larger) than the source disk (in my case exactly one PE). I think that the extended PE is used at the end of the disk by DRBD internal metadata.
This seems to create problems on qemu live migration and online target storage moving.

I  tried using external metadata for DRBD and this let the source and destination disk for live migration of the same size, and the migration succeeded.

1) create a storage pool for your drbd data
2) create a storage pool for your drbd metadata. You could use the same pool name (same volume group of data)
3) create the resource group property StorPoolNameDrbdMeta pointing to your metadata storage pool

_ex:_
`linstor resource-group set-property <yourResourceGroupName> StorPoolNameDrbdMeta <yourSharedPoolName>`

**Comment by megabert** [comment]
Two comments: 

1. This bug also applies to online migration to/from zfs storage
2. I would appreciate when unresolved bugs will be kept open (maybe with minimal priority).

**Comment by rck** [comment]
but this should be fixed in the latest release. are you using the latest release and did you set `exactsize` temporarily to `yes`?

**Comment by megabert** [comment]
I think I'm using the latest release. These are my used software versions for PVE, LinStor and DRBD:

```
drbd-dkms            9.2.10-1
drbd-utils           9.28.0-1
linstor-client       1.23.0-1
linstor-common       1.29.0-1
linstor-controller   1.29.0-1
linstor-proxmox      8.0.4-1
linstor-satellite    1.29.0-1
pve-manager          8.2.4
python-linstor       1.23.0-1
```

I did not set exactsize to yes. (This would provoke the problem, even if fixed, I suppose?).

**Comment by rck** [comment]
and as additional documentation for others that might find this issue later: `exactsize` is meant to be set **temporarily** , but it should be removed once the storage has been moved to DRBD. It is perfectly fine to set (and then reset) it whenever storage should be moved from $something to DRBD as needed, but should not be kept on. keeping it on will cause troubles later (e.g., on resize).

**Comment by ryan-ronnander** [comment]
[Related to this issue](https://forums.linbit.com/t/trying-to-move-vm-to-linstor-storage-storage-migration-failed-source-and-target-image-have-different-sizes/213/11?u=ryan), I'm seeing this issue present itself "the other way around" when trying to perform a live migration of a DRBD backed disk to local LVM. Copying the relevant section from the forum post here:

----
First, if I create a new disk for a running VM backed by LINSTOR with the `exactsize yes` parameter specified in `/etc/pve/storage.cfg`, I can move this disk image back and forth between LVM ↔ LINSTOR repeatedly without issue while the VM is running. Everything works as expected here.

However, `exactsize yes` is only supposed to be temporarily set for migration…

On the flipside, creating a new disk image for a running VM backed by LINSTOR with `exactsize no` presents an issue. Trying to move from a running VM’s disk from LINSTOR → LVM presents at this stage results in:

```
TASK ERROR: storage migration failed: block job (mirror) error: drive-virtio2: Source and target image have different sizes (io-status: ok)
```

So, when prepping for migration and toggling `exactsize yes` in `/etc/pve/storage.cfg`, and also ensuring that the current resource definition is adjusted (`linstor rd set-property <res_id> DrbdOptions/ExactSize yes`), migration still fails in Proxmox:

```
TASK ERROR: storage migration failed: block job (mirror) error: drive-virtio2: Source and target image have different sizes (io-status: ok)
```
