### ISSUE TITLE
DRBD/LINSTOR doesn't show up in PROXMOX  Datacenter > Storage > Add

### ISSUE THREAD

**Issue by Softlution2** [LINBIT/linstor-proxmox#56]
Hi. I have configured DRBD9 with Linstor in PROXMOX but so far I was only able to create a Proxmox LVM that works for VMs only. Proxmox Containers need a Filesystem so it doesn't work. Is DRBD or LINSTOR supposed to show up in Datacenter > Storage > Add   ? How do I use the DRBD/LINSTOR storage in VMs and Containers ?

**Comment by acidrop** [comment]
I'm using LINSTOR with DRBD9 on Proxmox since a long time now and I can confirm that it works both for creating VMs and Containers. I followed proxmox section in linstor user guide to setup the cluser.

https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#ch-proxmox-linstor

**Comment by rck** [comment]
> Is DRBD or LINSTOR supposed to show up in Datacenter > Storage > Add ?

IIRC no, that would require changes to dynamically extend the GUI, there is currently not API that would allow custom plugins to add themselves there. There has been some talk on the proxmox ML, but nobody stepped forward to do the actual implementation.

> How do I use the DRBD/LINSTOR storage in VMs and Containers ?

you just click through the "create VM" wizzard and select the storage you defined in `storage.cfg`
