### ISSUE TITLE
Snapshot with RAM not working

### ISSUE THREAD

**Issue by Jsiajake** [LINBIT/linstor-proxmox#59]
Snapshots with RAM don't work with linstor-proxmox 8.0.1, Proxmox 8.2.2

I receive the following error

TASK ERROR: allocated name ('vm-104-state-xbcvb') has to be a valid UUID or legacy name, or cloud-init name at /usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm line 381.

Snapshots without ram included work just fine

snapshotting 'drive-scsi0' (nvme-storage:pm-be4f3d1f_104)
TASK OK

It looks like it might have to do with the naming change recently, as the allocated name for the disk it’s attempting to create is vm-104-state-, and not the linstor uuid name.

Proxmox 8.2.2

**Comment by rck** [comment]
thanks for the report and I'm pretty sure you are right. I will try to fix that ASAP, should be simple enough

**Comment by rck** [comment]
fixed in 8.0.2 with https://github.com/LINBIT/linstor-proxmox/commit/bf12e8975e935b38f0388caef1cef451120b16f0

**Comment by adoerler** [comment]
@rck 
thanks for the fix in 8.0.2

In my opinion the [regex](https://github.com/LINBIT/linstor-proxmox/commit/bf12e8975e935b38f0388caef1cef451120b16f0#diff-17ed40c9f17b5196d0812add7700d6d4f0f4ab1c55168f8003058888e16fe9b1L23) `/^vm-\d+-state-.+\z/` should read `/^vm-\d+-state-.+\z/i` to ignore case.

Proxmox-UI allows entering uppercase `SNAPNAME`. Creating a snapshot will fail, if one uses e.g. `TEST` as name while the RAM option is active.
