### ISSUE TITLE
Name given by proxmox-csi-plugin is not allowed by linstor-proxmox

### ISSUE THREAD

**Issue by adoerler** [LINBIT/linstor-proxmox#61]
Hi,

we are evaluating `linstor-proxmox` on Proxmox 8.2.2 in combination with Talos and `proxmox-csi-plugin`.

When using [proxmox-csi-plugin](https://github.com/sergelogvinov/proxmox-csi-plugin) to provision persistent volumes for Kubernetes running as VMs on Proxmox, proxmox-csi-plugin creates disk named like:
 `vm-9999-pvc-124c0df4-16f5-46bc-a295-ecd24f145fb2'`.

Provisioning fails as this name is not allowed by `linstor-proxmox`.

The error is like:
```
failed to create vm disk: 500 allocated name ('vm-9999-pvc-124c0df4-16f5-46bc-a295-ecd24f145fb2') has to be a valid UUID, legacy, state, or cloud-init name at /usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm line 384
```

None of the regexes provided in [PluginHelper.pm](https://github.com/LINBIT/linstor-proxmox/blob/master/LINBIT/PluginHelper.pm) allows such a name.

The [controller](https://github.com/sergelogvinov/proxmox-csi-plugin/blob/76c899e4e1c8f2287854a4e08fbbdd8a1c7360a9/pkg/csi/controller.go#L188) of `proxmox-cis-plugin` creates the name like this:

```
vol := volume.NewVolume(region, zone, params[StorageIDKey], fmt.Sprintf("vm-%d-%s", vmID, pvc))
```

Where `vmID` is hardcoded to `9999` and `pvc` equals `request.GetName()` from the csi request, which seems to be `pvc-<UUID>` provided by Kubernetes.

Would you consider adding another regex or should we try to ask on `proxmox-cis-plugin` side for a way to configure the naming of the disks?

Best regards and many thanks in advance!

Andreas

**Comment by rck** [comment]
can you test the version from the `rck/pvc` branch ( https://github.com/LINBIT/linstor-proxmox/tree/rck/pvc ) please:

```
git fetch
git checkout -b rck/pvc origin/rck/pvc
scp LINSTORPlugin.pm root@${HOST}:/usr/share/perl5/PVE/Storage/Custom/
scp ./LINBIT/PluginHelper.pm root@${HOST}:/usr/share/perl5/LINBIT/PluginHelper.pm
ssh root@${HOST} "systemctl restart pvedaemon"
```

**Comment by adoerler** [comment]
Hi @rck ,

> an you test the version from the rck/pvc branch

thanks you!

I can confirm that the version in branch `rck/pvc` works :-)

I'm not sure if you've been notified about [my comment](https://github.com/LINBIT/linstor-proxmox/issues/59#issuecomment-2133696280) in the closed issue. 

I think the `valid_state` regex should either read:

```
sub valid_state_name {
    $_[0] =~ /^vm-\d+-state-.+\z/i
}
```

to allow uppercase snapshot  names or you should ensure (which would be even better) that the snapshot name provided by Proxmox gets converted to lower case characters.

**Comment by rck** [comment]
I saw that one and thanks, I might squeeze in one of the variants. I like the "convert to lowercase" a bit more. In general I think the limitation as it is now is fair, then users just have to play according the rules the plugin has and using only lowercase names is not the end of the world. There are a lot more limitations, funny users could also trigger names not valid on DRBD or LINSTOR level. Or maybe names not valid on ZFS/LVM level and so on. "do stupid things, get stupid results"

**Comment by rck** [comment]
fixed in https://github.com/LINBIT/linstor-proxmox/commit/70868c06757a539bd444492a90b879abae341dbf and v8.0.3
