### ISSUE TITLE
Online resize disk.

### ISSUE THREAD

**Issue by toalchers** [LINBIT/linstor-proxmox#7]
http://lists.linbit.com/pipermail/drbd-user/2018-September/024503.html

Add sleep(5)  and online resize (when VM is running) is working.

    $size = ( $size / 1024 ) . 'kiB';
    linstor_cmd(
        $scfg,
        [ 'volume-definition', 'set-size', $volname, 0, $size ],
        "Could not resize $volname"
    );
    sleep(5);
    return 1;

**Comment by rck** [comment]
@toalchers: Just to be sure, you got exactly that failure from the ML, and the sleep-5 then fixed it?

**Comment by toalchers** [comment]
> 
> 
> @toalchers: Just to be sure, you got exactly that failure from the ML, and the sleep-5 then fixed it?

Yes.

After volume_resize in LINSTORPlugin.pm -> qemu_block_resize in QemuServer.pm:

QemuServer.pm

```
sub qemu_block_resize {
    my ($vmid, $deviceid, $storecfg, $volid, $size) = @_;
    my $running = check_running($vmid);
    $size = 0 if !PVE::Storage::volume_resize($storecfg, $volid, $size, $running);
    return if !$running;
    vm_mon_cmd($vmid, "block_resize", device => $deviceid, size => int($size));
}

```

**Comment by rck** [comment]
Yes, I'm aware of the call-tree, and I had exactly that sleep-5 in my code on Fri. But it did not help and and it does not help now. But, we found out that resize in LINSTOR is not that synchronous as we thought. So yes, there is some race. Guess I add such a generous sleep to get the release out and remove it when this got changed in LINSTOR.

**Comment by rck** [comment]
Should be fixed in newest LINSTOR server release.
