### ISSUE TITLE
Disk size mismatch (LVM vs DRBD).

### ISSUE THREAD

**Issue by toalchers** [LINBIT/linstor-proxmox#8]
Create disk 10 GiB on LVM storage.
Create disk 10 GiB on DRBD storage.

#lvs --units B
vm-100-disk-0          pve      Vwi-a-tz-- 10737418240B
vm-100-disk-1_00000    drbdpool Vwi-aot--- 10741612544B

LVM
#qemu-img info /dev/mapper/pve-vm--100--disk--0
virtual size: 10G (10737418240 bytes)

DRBD
#qemu-img info /dev/drbd/by-res/vm-100-disk-1/0
virtual size: 10G (10739277824 bytes)

**Comment by rck** [comment]
Looks okay to me, DRBD needs space for its meta-data. So the backing devices are larger than the size presented to the user.
