### ISSUE TITLE
Removing snapshot fails

### ISSUE THREAD

**Issue by elonen** [LINBIT/linstor-proxmox#9]
Trying to remove a snapshot, I get:
`TASK ERROR: error with cfs lock 'storage-drbdlinstor': Could not remove vm-105-state-vanilla: got lock timeout - aborting command`

This stops me from migrating the VM, as the snapshot in question apparently contains a mounted reference to an ISO image not present on the other server.

**Comment by rck** [comment]
What do you mean by "apparently contains a mounted reference to an ISO image"? Where would that reference be? In LINSTOR a snapshot is just a snapshot of all backing devices + an object that tracks that. If it is in some "Proxmox meta data", then what should be storage plugin do about it?

**Comment by elonen** [comment]
I don't really know enough about Proxmox internals, but yes, the error message did look like it was some sort of Proxmox meta data. If it's on lower level than the plugin API then yeah, probably more of a Proxmox issue. Closing this.
